config/routes.rb
Rails.application.routes.draw do
  resources :stiffeners
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ibeam.rb
class Ibeam
  include Mongoid::Document
  field :_id, type: Integer
  field :Type, type: String
  field :Assigned, type: Boolean
  
  belongs_to :stiffener
end

app/models/stiffener.rb
class Stiffener
  include Mongoid::Document
  field :Pos, type: String
  field :Height, type: Float
  field :Width, type: Float
  field :Chamfer, type: Float
  
  has_many :ibeams
  
  accepts_nested_attributes_for :ibeams, :allow_destroy => false, :autosave => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/stiffeners_controller.rb
class StiffenersController < ApplicationController
  before_action :set_stiffener, only: [:show, :edit, :update, :destroy]

  # GET /stiffeners
  # GET /stiffeners.json
  def index
    @stiffeners = Stiffener.all
  end

  # GET /stiffeners/1
  # GET /stiffeners/1.json
  def show
  end

  # GET /stiffeners/new
  def new
    @stiffener = Stiffener.new
    @stiffener.ibeams.build
  end

  # GET /stiffeners/1/edit
  def edit
  end

  # POST /stiffeners
  # POST /stiffeners.json
  def create
    @stiffener = Stiffener.new(stiffener_only_params)
    puts stiffener_params[:ibeams_attributes]["0"][:Type]
    Ibeam.any_in(:_id => stiffener_params[:ibeams_attributes]["0"][:Type]).update_all(:Assigned => true, :stiffener_id => @stiffener._id)
  
    respond_to do |format|
      if @stiffener.save
        format.html { redirect_to stiffeners_url, notice: 'Stiffener was successfully created.' }
        format.json { render :show, status: :created, location: @stiffener }
      else
        format.html { render :new }
        format.json { render json: @stiffener.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stiffeners/1
  # PATCH/PUT /stiffeners/1.json
  def update
    respond_to do |format|
      if @stiffener.update(stiffener_params)
        format.html { redirect_to @stiffener, notice: 'Stiffener was successfully updated.' }
        format.json { render :show, status: :ok, location: @stiffener }
      else
        format.html { render :edit }
        format.json { render json: @stiffener.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stiffeners/1
  # DELETE /stiffeners/1.json
  def destroy
    puts 'run'
    Ibeam.any_in(:stiffener_id => @stiffener._id).update_all(:Assigned => false, :stiffener_id => nil)
    @stiffener.destroy
    respond_to do |format|
      format.html { redirect_to stiffeners_url, notice: 'Stiffener was successfully destroyed.' }
      format.json { head :no_content }
    end
    respond_to do |format|
      format.html
      format.json
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stiffener
      @stiffener = Stiffener.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stiffener_params
      params.require(:stiffener).permit(:id, :Pos, :Height, :Width, :Chamfer, :ibeams_attributes => [:_id, {:Type => []}, :_destroy])
    end
    def stiffener_only_params
      params.require(:stiffener).permit(:Pos, :Height, :Width, :Chamfer)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stiffeners_helper.rb
module StiffenersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prosteeldb</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--<link href="https://fonts.googleapis.com/css?family=Lora" rel="stylesheet" type="text/css">-->
  </head>

  <body>
    <nav class="navbar navbar-default fixed-top navbar-bg">
      <div class="container-fluid">
        <div class="navbar-header">
          <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">CAD Tools</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li class="active"><a href="#">About</a></li>
            <li class="active"><a href="#">Contact</a></li>
          </ul>
        </div>
      </div>
    </nav>
    
    <div class="container-fluid container-main-content">
      
      <div class="row" style="height: 100%">
        
        <div class="col-xs-12 col-sm-12" style="height: 100%">
          <%= yield %>
        </div>
        
      </div>

    </div>
  </body>
</html>

app/views/stiffeners/_form.html.erb
<div class="form-new-stiffener">
  <div class="form-header">
    <h4 class="h4-page-name">New Stiffener</h3>
  </div>
  <div class="form-main-part" id="form-main-part-new-stiffener">
    <%= form_with(model: stiffener, local: true, class: "form-horizontal", id: "form-create-stiffener") do |form| %>
    
      <div class="form-group">
        <%= form.label :Pos, 'Position Number', class: "col-xs-7 col-sm-7 control-label", style: "text-align: left;" %>
        <div class="col-xs-5 col-sm-5">
          <%= form.text_field :Pos, class: "form-control", id: :stiffener_Pos, placeholder: "sv1" %>
        </div>
      </div>
    
      <div class="form-group">
        <%= form.label :Height, class: "col-xs-7 col-sm-7 control-label", style: "text-align: left;" %>
        <div class="col-xs-5 col-sm-5">
          <%= form.text_field :Height, class: "form-control", id: :stiffener_Height, placeholder: "Height, inch" %>
        </div>
      </div>
    
      <div class="form-group">
        <%= form.label :Width, class: "col-xs-7 col-sm-7 control-label", style: "text-align: left;" %>
        <div class="col-xs-5 col-sm-5">
          <%= form.text_field :Width, class: "form-control", id: :stiffener_Width, placeholder: "Width, inch" %>
        </div>
      </div>
    
      <div class="form-group">
        <%= form.label :Chamfer, class: "col-xs-7 col-sm-7 control-label", style: "text-align: left;" %>
        <div class="col-xs-5 col-sm-5">
          <%= form.text_field :Chamfer, class: "form-control", id: :stiffener_Chamfer, placeholder: "Chamfer, inch" %>
        </div>
      </div>
      
      <div class="dual-listbox">
        <%= label_tag("dual-listbox", "Assign I-beams to the stiffener:", class: "dual-listbox-label") %>
        <%= form.fields_for :ibeams do |ibeam_fields| %>
          <div class="form-group">
            <div class="col-xs-5 col-sm-5">
              <%= select_tag :shapes, options_from_collection_for_select(Ibeam.where(:Assigned => false).asc(:_id), "_id", "Type"), {:class => "form-control", :id => "listbox1", :include_blank => false, :include_hidden => false, :multiple => true, :size => 10} %>
            </div>
            <div class="col-xs-2 col-sm-2 arrow-buttons">
              <%= button_tag(:type => 'button', :id => 'btn-arrowRight', :class => 'btn btn-default') do %>
              <%= content_tag(:span, nil, :class => 'glyphicon glyphicon-menu-right') %>
              <% end %>
              <br></br>
              <%= button_tag(:type => 'button', :id => 'btn-arrowLeft', :class => 'btn btn-default') do %>
              <%= content_tag(:span, nil, :class => 'glyphicon glyphicon-menu-left') %>
              <% end %>
            </div>
            <div class="col-xs-5 col-sm-5">
              <%= ibeam_fields.select :Type, [], {:include_blank => false, :include_hidden => false}, {:class => "form-control", :id => "listbox2", :multiple => true, :size => 10} %>
            </div>
          </div>
        <% end %>
      </div>
      
      <!--<% if stiffener.errors.any? %>-->
      <!--  <div id="error_explanation">-->
      <!--    <h2><%= pluralize(stiffener.errors.count, "error") %> prohibited this stiffener from being saved:</h2>-->
    
      <!--    <ul>-->
      <!--    <% stiffener.errors.full_messages.each do |message| %>-->
      <!--      <li><%= message %></li>-->
      <!--    <% end %>-->
      <!--    </ul>-->
      <!--  </div>-->
      <!--<% end %>-->
      
    <% end %>
    <div class="actions pull-right">
      <%= button_tag 'Create stiffiner', :type => 'button', class: "btn btn-default", id: "btn-create-stiffener" %>
      <%= link_to 'Back', stiffeners_path, class: "btn btn-default", id: "btn-back" %>
    </div>
  </div>
</div>

app/views/stiffeners/edit.html.erb
<h3 class='h3-page-name'>Editing Stiffener</h1>

<%= render 'form', stiffener: @stiffener %>

<%= link_to 'Show', @stiffener %> |
<%= link_to 'Back', stiffeners_path %>

app/views/stiffeners/index.html.erb
<div class="list-of-stiffeners">
  <div class="form-header">
    <h4 class="h4-page-name">List of stiffeners</h4>
  </div>
  <div class="form-main-part" id="list-of-stiffeners-main-part">
    <table class="table table-fixed" id="table-of-stiffeners">
      <thead>
        <tr class="head-row">
          <th scope="col">Pos</th>
          <th scope="col">Height</th>
          <th scope="col">Width</th>
          <th scope="col">Chamfer</th>
          <th scope="col">Beams</th>
          <th scope="col"></th>
        </tr>
      </thead>
      
      <tbody>
        <% @stiffeners.each do |stiffener| %>
          <tr class="record-row" id="row-<%= stiffener._id %>">
            <th scope="row"><%= stiffener.Pos %></th>
            <td><%= stiffener.Height %></td>
            <td><%= stiffener.Width %></td>
            <td><%= stiffener.Chamfer %></td>
            <td>
            <% stiffener.ibeams.each do |b| %>
            <p><%= b.Type %></p>
            <% end %>
            </td>
            <td>
              <!--<%= link_to stiffener, :class => 'btn btn-default btn-show' do %>-->
              <!--<%= content_tag(:span, nil, :class => 'glyphicon glyphicon-eye-open') %>-->
              <!--<% end %>-->
              <!--<%= link_to edit_stiffener_path(stiffener), :class => 'btn btn-default btn-edit' do %>-->
              <!--<%= content_tag(:span, nil, :class => 'glyphicon glyphicon-edit') %>-->
              <!--<% end %>-->
              <!--<%= link_to stiffener, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-default btn-destroy' do %>-->
              <!--<%= content_tag(:span, nil, :class => 'glyphicon glyphicon-remove-sign') %>-->
              <!--<% end %>-->
              <%= button_tag(:type => 'button', :class => "btn btn-default btn-destroy", :id => stiffener._id) do %>
              <%= content_tag(:span, nil, :class => 'glyphicon glyphicon-remove', :id => stiffener._id) %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    <%= link_to 'New Stiffener', new_stiffener_path, :class => 'btn btn-default btn-new-stiffener pull-right', :id => 'btn-new' %>
  </div>
</div>
<!--<div class="cell-C2">-->
<!--  <p id="notice"><%= notice %></p>-->
<!--</div>-->

app/views/stiffeners/new.html.erb
<%= render 'form', stiffener: @stiffener %>

app/views/stiffeners/show.html.erb
<div class="cell-C1">
  <p>
  <strong>Pos:</strong>
  <%= @stiffener.Pos %>
  </p>
  
  <p>
    <strong>Height:</strong>
    <%= @stiffener.Height %>
  </p>
  
  <p>
    <strong>Width:</strong>
    <%= @stiffener.Width %>
  </p>
  
  <p>
    <strong>Chamfer:</strong>
    <%= @stiffener.Chamfer %>
  </p>
  
  <%= link_to 'Edit', edit_stiffener_path(@stiffener) %> |
  <%= link_to 'Back', stiffeners_path %>
</div>

<div class="cell-C2">
  <p id="notice"><%= notice %></p>
</div>